- src/App.vue
- src/components/MapView.vue
MapViewをMapとSpotInfoの親コンポーネントとして追加しました
確認お願いします
> MapViewの追加

- .gitignore
- package-lock.json
- package.json
- TypeDocを追加しました
- 仕様に従ってコメントを記述することで華やかな見た目のドキュメントが生成される便利なやつです
- ``npm run typedoc``でドキュメントがdocsディレクトリに生成されます（初回はnpm installを忘れずに）
- docsは".gitignore"に入れてます
- https://typedoc.org/guides/doccomments/
- これを参考に各メソッドとクラスにコメントお願いします
- ~~実際はドキュメントの生成はどうでも良くて，コメントそのものを記述することが目的です~~
- 参考
[よくわかるホニャララDoc](https://qiita.com/maku77/items/6410c67ce95e08d8d1bd)
> TypeDocの追加

- ISSUE_TEMPLATE.md
> issueテンプレー更新第一案

- package-lock.json
- src/store/modules/MapViewModule.ts
- src/store/types.ts
- tests/unit/store/modules/MapViewModule.spec.ts
> Update spot for map vuex

- src/components/Map.ts
- tests/unit/mapSwitchMarkers.spec.ts
> types.tsにNode型とEdge型の追加

- src/components/Map.ts
- vuexではなくmapコンポーネントがメンバで持つようにした
- 初期値はrootMapId
close #116
> mapIdToDisplayをmapコンポに追加

- src/components/Map.ts
- tests/unit/mapUpdateDisplayLevel.spec.ts
- zoomlevelの閾値作成(仮で19にしてます)
- updateDisplayLevel作成
- 閾値以上なら```'detail'```
- 閾値未満なら```'default'```
- をstateにセットする
- this.mapにコールバック登録(ズーム後のzoomlevelが見たいのでzoomendのイベントで登録しています)
- テスト作成
close #114
> ズームレベルが変更された時にstateのdisplayLevelを変更するコールバック作成

- src/store/modules/sampleMaps.ts
- 表示テストには```MapViewModule.ts```の```rootMapId```を2に指定してください．
- 総合学習プラザの2Fのマップidが1Fと同じになっていたので修正しました
close #104
> 総合学習プラザ206~210の座標データ作成

- src/components/Map/index.ts
- displayPolygonsの引数を変更
- mapid(number) -> (SpotsForMap[])
- #122の変更に合わせて変更しています
- 前のプルリク#144はmasterを取り込む時にコンフリクトが発生してくれなかったので作り直しました
close #72
> ポリゴン表示関数のアップデート

- src/components/Map/index.ts
- zoomControl(拡大縮小ボタン)の配置を右下へ変更
close #167
> zoomControlを右下に移動

- src/components/MapView/index.vue
- src/components/SearchBox/index.ts
- src/components/SpotSearch/index.ts
- src/components/SpotSearch/index.vue
- tests/unit/components/SearchBox/searchBox.spec.ts
- searchWordを監視して，親コンポーネント（SpotSearch）にエミットする
close #152
> searchBoxの変更をSpotSearchに通知する

- src/components/MapView/index.vue
- src/components/SpotInfoCard/index.vue
SpotInfoコンポーネントをレスポンシブにしました。
SpotInfoCardのisVisibleをtrueにすると表示されます。
画面サイズによってコンポーネントの横幅が変化します。
close #186
> spotInfoのサイズが画面サイズで切り替わるように修正

- src/store/modules/sampleMaps.ts
sampleMapsのデータを修正しました．
- 名前を日本語に
- ウエスト2号館のdetailMapIds, FloorNames追加
- 不要なデータ削除
close #189
> ウエスト2号館のdetailMapIds, floorNames追加 & 名前を日本語に修正

- src/store/modules/sampleMaps.ts
> スポットの名前を日本語に修正

- src/components/Map/Marker/CurrentLocationMarker.ts
- src/components/Map/Marker/DefaultSpotMarker.ts
- src/components/SpotSearch/index.vue
- マーカーのアイコンをマテリアルアイコンに変更しました
- クリックした時にマップ側から呼び出せるアイコンの色を変更できる関数を実装しました
- ```updateFocusedMarker```内に```this.setSelected(true);```を書いてマーカーをクリックして色の変更ができるかの確認お願いします
close #205
> マテリアルアイコンに変更，選択した時の色を変える関数実装

- src/components/Map/index.ts
> マップの移動をsetViewからflyToに変更

- src/store/modules/sampleMaps.ts
いくつかdescription書いてみたのでよかったらマージしてください
> spotのdescription追加

- src/Map/Map.ts
- src/Spot/Spot.ts
- Spot, Mapクラスを作成
close #255, #256
> Spotクラス, Mapクラスの雛形作成

- src/Components/MainCreationView/index.vue
- src/components/CreationMainView/index.vue
Co-authored-by: shuto410 <takumi.shuto314@gmail.com>
Co-authored-by: nishikawa1122 <nishikawa@posl.ait.kyushu-u.ac.jp>
地図作成関連のコンポーネントを配置する親コンポーネントとしての雛形を作成
**コンポーネント名がしっくりきてないので代替案があればよろしくお願いします**
(案: MainCreateView, MapCreateMainView？<-長い) 
close #284
> 地図作成コンポーネントの雛形作成

- src/components/MapSearch/index.ts
- MapSearchコンポーネントでsearchクラスの拡張に対応
close #367
> コンパイルエラーの修正
